### ISSUE TITLE
有没有办法实现SE的自动转换呢？

### ISSUE THREAD

**Issue by ykk648** [xiezheng-cs/PytorchToCaffe#1]
最好是使用作者开发的模块  https://github.com/hujie-frank/SENet
具体思路可以分享一下吗？

**Comment by ykk648** [comment]
如果有思路的话 ：）

**Comment by ykk648** [comment]
用你的方法成功转换了SE，conv或者fc两种SE的实现都可以。

**Comment by xiezheng-cs** [comment]
> 用你的方法成功转换了SE，conv或者fc两种SE的实现都可以。

因为我已经踩过这些坑，转成功了
